import colors from './index';

const palette = {
  backdrop: colors.hack0dark,
  foreground: colors.hack0,
  topBar: colors.hack0,
  headerTintColor: colors.white,
  bottomBar: colors.hack0,
  barBorder: colors.grey,
  barIconActive: colors.blush,
  barIconInactive: colors.darkGrey,
  actionDefault: colors.blueLightGrey,
  actionHero: colors.blush,
  actionPrimary: colors.blue,
  actionSuccess: colors.green,
  actionWarning: colors.orange,
  actionDanger: colors.red,
  switchActive: colors.blueGreen,
  switchInactive: colors.grey,
  separator: colors.greyPurple,
  inputBackground: colors.blueGrey,
  inputPlaceholder: colors.darkGrey,
  text1: colors.white,
  text2: colors.grey,
  text3: colors.darkGrey,
  text4: colors.darkestGrey,
  messageBubble: colors.hack2,
  ownMessageBubble: colors.hack1,
  messageSender: colors.lightgrey,
  messageBody: colors.white,
  checkBox: colors.white,
  quoteSeparator: colors.white,
};

export default palette;
